# Generated by Django 3.0.3 on 2020-02-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersummaries',
            options={'ordering': ['id']},
        ),
    ]
